In [2]:
import numpy as np

In [3]:
x =[1,2,3]
y =[4,5,6]

z = []
for i in range(len(x)):
    z.append(x[i] + y[i])
z

[5, 7, 9]

In [4]:
# vector as array
x =np.array([1,2,3])
x

array([1, 2, 3])

In [5]:
list(range(1,4))

[1, 2, 3]

In [6]:
np.arange(1,4)

array([1, 2, 3])

In [7]:
type(x)

numpy.ndarray

##### Vector addition

In [8]:
x =np.array([1,2,3])
y =np.array([4,5,6])

z = x + y
z

array([5, 7, 9])

##### Element-wise multiplication

In [9]:
x =np.arange(1,4)
y =np.arange(4,7)

z = x * y
z

array([ 4, 10, 18])

##### Scaling vectors

In [10]:
x =np.arange(1,4)
y = 3 * x
y

array([3, 6, 9])

##### Python Lists vs Numpy Arrays

In [13]:
x_lists =list(range(1,1_000_001))
x_numpy =np.arange(1,1_000_001)

In [14]:
%timeit [2* comp for comp in x]

262 ms ± 21.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
%timeit 2 * x_numpy

9.7 ms ± 2.46 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [16]:
262 /9.7

27.01030927835052

##### Element-wise functions of vectors

In [ ]:
## squre 
x =np.arange(1,5)
y = x **2
y

array([ 1,  4,  9, 16])

In [20]:
## Taking log10
x = np.array([1,10,100,1000,10_000,100_000])
y =np.log10(x)
y

array([0., 1., 2., 3., 4., 5.])

In [21]:
## taking log to base e
x = np.array([1,np.e,np.e**2,np.e**3])
y =np.log(x)
y

array([0., 1., 2., 3.])

In [ ]:
## addition of scalar in each element
x=np.array([1,2,3])
c =5
y = x + c
y

array([6, 7, 8])

In [24]:
## f(x) =5x-2
x =np.array([-1,0,1,2])
y = 5*x - 2
y

array([-7, -2,  3,  8])

##### Dot product

In [25]:
x =np.arange(1,5)
y =np.arange(-4,-8,-1)

x @ y

np.int64(-60)

In [ ]:
x =np.arange(1,5)
y =np.arange(-4,-8,-1)

x.T @ y  ## T = transpose

np.int64(-60)

In [27]:
## another way
np.dot(x,y)

np.int64(-60)

##### Vector of Zeros or ones

In [30]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [31]:
ones =np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [32]:
five = np.ones(5)*5
five

array([5., 5., 5., 5., 5.])

##### Norms of a vectors

In [ ]:
x =np.array([1,2,3])
np.linalg.norm(x)   ## L2 norm

np.float64(3.7416573867739413)

In [35]:
x =np.array([1,2,3])
np.linalg.norm(x,ord=1)  ## L1 norm

np.float64(6.0)

##### Shape and dimension of a vector

In [36]:
x =np.array([1,2,3,4])
x.shape

(4,)

In [37]:
x.ndim

1