In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x = np.linspace(0,1,11)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [4]:
x.shape

(11,)

In [5]:
x=np.linspace(0,1,5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.arange(0,1.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])