In [2]:
!pip install numpy

In [3]:
import numpy as np

##### 1 . 1D array

In [4]:
one_dimensional_arr =np.array([10,20])
print(one_dimensional_arr)

[10 20]


In [6]:
a =np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
# Create an array with 3 integers, starting from the default integer 0
b =np.arange(3)
print(b)

[0 1 2]


In [8]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3
c =np.arange(1,20,3)
print(c)

[ 1  4  7 10 13 16 19]


In [9]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [10]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [11]:
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [12]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [14]:
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype)  # his array holds text of length up to 23 characters.”

['Welcome to Math for ML!']
<U23


In [15]:
# Return a new array of shape 3, filled with ones. 
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [16]:
# Return a new array of shape 3, filled with zeroes.
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [17]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [18]:
# Return a new array of shape 3 with random numbers between 0 and 1.
rand_arr = np.random.rand(3)
print(rand_arr)

[0.50170909 0.56536039 0.57222726]


##### 2 - Multidimensional Arrays

In [19]:
# Create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [20]:
# 1-D array 
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                    one_dim_arr, # the array to be reshaped
                    (2,3) # dimensions of the new array
                )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


<a name='2-1'></a>
#### 2.1 - Finding size, shape and dimension. ###

In [22]:
# Dimension of the 2-D array multi_dim_arr
# ndarray.ndim - Stores the number dimensions of the array.
multi_dim_arr.ndim

2

In [23]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_arr.shape

(2, 3)

In [24]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_arr.size

6

<a name='3'></a>
#### 3 - Array math operations #

In [25]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


<a name='3-1'></a>
#### 3.1 - Multiplying vector with a scalar (broadcasting) ##

In [26]:
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

<a name='4'></a>
#### 4 - Indexing and slicing #

#### 4.1 - Indexing ##

In [27]:
# Select the third element of the array. Remember the counting starts from 0.
a = np.array([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


In [28]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j and two sets of brackets
print(two_dim[2][1])

# Select element number 8 from the 2-D array, this time using i and j indexes in a single 
# set of brackets, separated by a comma
print(two_dim[2,1])

8
8


<a name='4-2'></a>
#### 4.2 - Slicing ##
The syntax is:

`array[start:end:step]`

In [34]:
a =np.array([1,2,3,4,5])
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2 3 4]


In [35]:
# Slice the array a to get the array [1,2,3]
sliced_arr = a[:3]
print(sliced_arr)


[1 2 3]


In [36]:
# Slice the array a to get the array [3,4,5]
sliced_arr = a[2:]
print(sliced_arr)

[3 4 5]


In [37]:
# Slice the array a to get the array [1,3,5]
sliced_arr = a[::2]
print(sliced_arr)

[1 3 5]


In [38]:
# Note that a == a[:] == a[::]
print(f'a == a[:]: {a == a[:]}')
print(f'a[:] == a[::]: {a[:] == a[::]}')

a == a[:]: [ True  True  True  True  True]
a[:] == a[::]: [ True  True  True  True  True]


In [39]:
# Slice the two_dim array to get the first two rows
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
# Similarily, slice the two_dim array to get the last two rows
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [41]:
# This example uses slice notation to get every row, and then pulls the second column.
# Notice how this example combines slice notation with the use of multiple indexes
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


<a name='5'></a>
#### 5 - Stacking #

- `np.vstack()` - stacks vertically
- `np.hstack()` - stacks horizontally
- `np.hsplit()` - splits an array into several smaller arrays

In [42]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [43]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)


[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [44]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [45]:
# Split the horizontally stacked array into 2 separate arrays of equal size
horz_split_two = np.hsplit(horz_stack,2)
print(horz_split_two)

# Split the horizontally stacked array into 4 separate arrays of equal size
horz_split_four = np.hsplit(horz_stack,4)
print(horz_split_four)

# Split the horizontally stacked array after the first column
horz_split_first = np.hsplit(horz_stack,[1])
print(horz_split_first)

[array([[1, 1],
       [2, 2]]), array([[3, 3],
       [4, 4]])]
[array([[1],
       [2]]), array([[1],
       [2]]), array([[3],
       [4]]), array([[3],
       [4]])]
[array([[1],
       [2]]), array([[1, 3, 3],
       [2, 4, 4]])]


In [46]:
# Split the vertically stacked array into 2 separate arrays of equal size
vert_split_two = np.vsplit(vert_stack,2)
print(vert_split_two)

# Split the vertically stacked array into 4 separate arrays of equal size
vert_split_four = np.vsplit(vert_stack,4)
print(vert_split_four)

# Split the vertically stacked array after the first and third row
vert_split_first_third = np.vsplit(vert_stack,[1,3])
print(vert_split_first_third)

[array([[1, 1],
       [2, 2]]), array([[3, 3],
       [4, 4]])]
[array([[1, 1]]), array([[2, 2]]), array([[3, 3]]), array([[4, 4]])]
[array([[1, 1]]), array([[2, 2],
       [3, 3]]), array([[4, 4]])]
