#### Representing Systems of Equations as Matrices

In [1]:
import numpy as np


In [7]:
A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]


In [8]:
print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")

# print(f"Shape of A: {np.shape(A)}")
# print(f"Shape of A: {np.shape(b)}")

Shape of A: (2, 2)
Shape of b: (2,)


In [9]:
x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [-1.  2.]


<a name='1.3'></a>
#### 1.3 - Evaluating Determinant of a Matrix

In [10]:
d = np.linalg.det(A)

print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -11.00


In [11]:
A_system = np.hstack((A, b.reshape((2, 1))))

print(A_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [12]:
print(A_system[1])

[3. 2. 1.]


<a name='3'></a>
#### 3 - System of Linear Equations with No Solutions

In [14]:
A_2 = np.array([
        [-1, 3],
        [3, -9]
    ], dtype=np.dtype(float))

b_2 = np.array([7, 1], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


In [15]:
A_2_system= np.hstack((A_2 ,b_2.reshape(2,1)))
print(A_2_system)

[[-1.  3.  7.]
 [ 3. -9.  1.]]


In [18]:
solve = np.linalg.solve(A_2,b_2)
print(solve)


LinAlgError: Singular matrix

In [19]:
try:
    x_2 = np.linalg.solve(A_2, b_2)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix


<a name='4'></a>
#### 4 - System of Linear Equations with an Infinite Number of Solutions

In [20]:
b_3 = np.array([7, -21], dtype=np.dtype(float))

In [22]:
A_3_system = np.hstack((A_2, b_3.reshape((2, 1))))
print(A_3_system)

[[ -1.   3.   7.]
 [  3.  -9. -21.]]
