In [2]:
import numpy as np

##### Array Creation

In [3]:
a = np.array([1,2,3])  
print(a)

## dimesion of array
print(a.ndim)

[1 2 3]
1


In [4]:
## MultiDimensional array (matrix)
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
## length of each dimension
b.shape

(2, 3)

In [6]:
## type of iteams
a.dtype

dtype('int64')

In [7]:
c =np.array([2.2,5,1.1])
print(c)

[2.2 5.  1.1]


In [8]:
# two arrays both the same shape but diffrent filter values
d =np.zeros((2,3))
print(d)
e =np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
## generate an array with random numnbers
np.random.rand(2,3)

array([[0.06132102, 0.2105694 , 0.89397936],
       [0.80841571, 0.09580277, 0.7733245 ]])

In [10]:
f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [11]:
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

##### Array Operation

In [12]:
## Arthimatic Operations
a =np.array([10,20,30,40])
b =np.array([1,2,3,4])

c = a- b
print(c)

d = a * b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [13]:
farenheit = np.array([0,-10,-5,-15,0])
celsius  =(farenheit-31)*(5/9)
print(celsius)

[-17.22222222 -22.77777778 -20.         -25.55555556 -17.22222222]


In [15]:
celsius > -20

array([ True, False, False, False,  True])

In [16]:
celsius % 2 ==0

array([False, False,  True, False, False])

In [17]:
# matrix product
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A @ B)

[[5 4]
 [3 4]]


In [19]:
## Element product
print(A*B)

[[2 0]
 [0 4]]


In [21]:
array1=np.array([[1,2,3],[4,5,6]])
print(array1.dtype)

array2= np.array([[1.2,2.3,1.2],[1.0,2.4,12.4]])
print(array2.dtype)


int64
float64


In [23]:
## addition of two arrays
array3= array1 + array2
print(array3)
print(array3.dtype)

[[ 2.2  4.3  4.2]
 [ 5.   7.4 18.4]]
float64


In [24]:
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

41.5
18.4
2.2
6.916666666666667


In [25]:
b = np.arange(1,16,1).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
